# Codecov.io configuration file
codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
 - "cpp-package/example/**/*"
 - "tests/**/*"

# Disable comments for now to gather data in the background
comment: false
#  layout: "header, diff"
#  behavior: default
#  require_changes: no
