sudo: true

language: cpp

cache:
  directories:
    - $HOME/.ccache
    - $HOME/.cache/pip
    - $HOME/.mxnet
    - $HOME/Library/Caches/Homebrew

os:
  - osx

osx_image: xcode9.4

matrix:
  include:
    - os: osx

before_install:
  - export PYTHONPATH=${PYTHONPATH}:${PWD}/python

install:
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install ccache
  - export PATH="/usr/local/opt/ccache/libexec:$PATH"
  - source ci/travis/install.sh

# We build with 2 concurrent jobs to match the number of cores present on MacOS virutal machines.
# nproc does not report the correct number of cores reliably in Travis, so using nproc is not
# recommended.
# https://docs.travis-ci.com/user/reference/overview/
script:
  - export MXNET_STORAGE_FALLBACK_LOG_VERBOSE=0
  - mv make/osx.mk config.mk
  - make -j 2

  # Temporarily disabled due to https://github.com/apache/incubator-mxnet/issues/13136
  # We ignore several tests to avoid possible timeouts on large PRs.
  # This lowers our test coverage, but is required for consistent Travis runs.
  # These tests will be tested in a variety of environments in Jenkins based tests.
#  - python -m nose --with-timer --exclude-test=test_sparse_operator.test_elemwise_binary_ops --exclude-test=test_gluon_model_zoo.test_models --exclude-test=test_random.test_shuffle --exclude-test=test_operator.test_broadcast_binary_op --exclude-test=test_operator.test_pick --exclude-test=test_profiler.test_continuous_profile_and_instant_marker --exclude-test=test_metric_perf.test_metric_performance --exclude-test=test_operator.test_order --verbose tests/python/unittest/
#  - python2 -m nose --verbose tools/coreml/test --exclude-test=test_mxnet_image
